apiVersion: v1
kind: Pod
metadata:
  name: demo-service
  labels:
    app: demo-service
  namespace: namespace1
spec:
  serviceAccountName: default
  containers:
  - name: demo-service
    image: amit4sun/demo-service:5.0
    ports:
    - containerPort: 80
